### ISSUE TITLE
Drivebase [502 Subsystem]

### ISSUE THREAD

**Issue by Avnzx** [bluesatunsw/owr-502#10]
## Description
This issue includes developing a model of the test robot for visualization using RViz, with simulation in Gazebo.

The deliverable for this will be a ROSBag file containing the requested and recorded velocities of the wheels, the recorded position of the wheels + a video to confirm this looks sane.

## Possible Implementations
Create Xacro definitions for the drivebase

[ROS2Control "DiffBot" Example](https://control.ros.org/master/doc/ros2_control_demos/example_2/doc/userdoc.html)

## Todo
- [x] Follow the [articulated robotics](https://articulatedrobotics.xyz/tutorials/mobile-robot/applications/ros2_control-concepts) tutorial up to the point where it uses a ROS2Control backend
- [x] Modify this URDF to fit our rover
- [ ] Find/Make a new ROS2Control Controller for our DB
  - Constrained swerve type
- [ ] Homing routine for fully sensorless steering
  - [ ] Use virtual (current sense) or real endstop (COMMUNICATE THIS TO ESC-WG **ASAP**)
- [ ] Allow switching between the Ros2Control->Gazebo backend and Ros2Control->Real hardware backends
  - [ ] Evaluate if an effort (torque) controller may be used for this
