### ISSUE TITLE
Get requirements for cameras

### ISSUE THREAD

**Issue by Avnzx** [bluesatunsw/owr-502#13]
## Description

We want multiple cameras around the robot, possibly some PTZ (Pan Tilt Zoom) cameras to allow the robot to inspect itself / be used when teleoperating the robot.

## Todo
Determine 
- [ ] Whether we want normal webcams (e.g. GoPro) or PoE cams
  - [ ] Do we want some of these to be depth cameras (e.g Realsense)
- [ ] What resolution / frame rate we need
  - [ ] Do we want the video be compressed on the camera to reduce BW over the radio link
- [ ] Do they need to be PTZ or will we be designing this ourselves
- [ ] What FOV do they need to have?
  - [ ] Do we need undistortion to happen onboard?
- [ ] What cost is acceptable per unit
- [ ] What kind of temperature/dust will they need to resist w/o overheating etc
- [ ] What power draw is acceptable
  - [ ] Do we need a method of commanding them to 'sleep'
- [ ] What kind of mounting schemes are acceptable
  - [ ] Screws, tape, etc?
