### ISSUE TITLE
ESC (B-G431B-ESC1) Improvements

### ISSUE THREAD

**Issue by Avnzx** [bluesatunsw/owr-502#15]
## Description
There are various improvements we need to make to our custom motor controllers of choice. This includes electrical, mechanical, and software improvements.

## Todo
In order of importance:
- [x] Use current sense as an encoder w/ the ["MXLEMMING" Observer](https://github.com/Candas1/Arduino-FOC-drivers/tree/flux_observer/src/encoders/MXLEMMING_observer)
- [x] #18
- [x] #26
- [x] #17
- [x] #29
- [x] #20
- [x] #21
- [x] Fix current sensing (check our shunt value+ADC gains), see if we need to add filtering
- [x] Figure out how to use the other sensors (primarily input voltage & temp)
- [ ] (Possibly) Switch off of the Arduino framework (w/PlatformIO) and use the HAL directly
- [ ] Regen and Static brake modes
- [ ] Report discordant motoring
- [ ] Soft and hard limits
